#!/usr/bin/env python3
"""Rebuild the site from the current R3000 data and stage it for deploy.

  python3 publish.py            rebuild dashboard from data, then stage
  python3 publish.py --no-build stage the existing HTML without regenerating

Everything under site/ is what gets uploaded. Nothing else does.
"""
import argparse, hashlib, json, re, shutil, subprocess, sys
sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent / "pipeline"))
import brand
from datetime import datetime
from pathlib import Path

HERE   = Path(__file__).resolve().parent
SITE   = HERE / "docs"      # GitHub Pages serves from root or /docs only
DOMAIN = "bilaalraja.com"
SRC    = HERE / "pipeline"   # build inputs, kept here so nothing depends on scratch dirs
PY     = "/Users/bilaa/Downloads/pitquant/.venv/bin/python"

PAGES = [                      # source file, url path, human title
    (SRC / "r3k_dashboard.html", "russell3000", "Russell 3000 Cross-Section"),
    (SRC / "commentary.html",    "commentary",  "Results Commentary"),
    # must stay after the dashboard: inject_meta reads the universe count that
    # only the dashboard entry populates.
    # The gate-exit rule is now the beta-capped book: same six-gate exit rule,
    # with the beta cap kept as a footnote. The old gate_exit.html essay is
    # retired, and /beta-capped/ redirects here.
    (SRC / "beta_book.html",     "gate-exit",   "The Gate Exit Rule"),
    (SRC / "rates.html",         "rates",       "US Treasury Yields"),
]

# Any Claude artifact link becomes a local path, so the site stands alone.
ARTIFACT_MAP = {
    "0c2545da-ee53-41ec-8763-583958244c94": "/commentary/",
    "ae70a1e5": "/russell3000/",
}


def meta_from_dashboard(html: str) -> dict:
    """Pull the META object the generator embedded, so the landing page shows
    exactly the same figures as the dashboard rather than its own guess."""
    m = re.search(r"META=(\{.*?\}), METRICS=", html, re.S)
    return json.loads(m.group(1)) if m else {}


def rewrite_links(html: str) -> tuple[str, int]:
    n = 0
    for uid, local in ARTIFACT_MAP.items():
        pat = re.compile(r'https://claude\.ai/code/artifact/' + uid + r'[^"\']*')
        html, k = pat.subn(local, html)
        n += k
    return html, n


# Cloudflare sits in front of this site and GitHub Pages serves images with
# max-age=14400, so a replaced icon kept serving stale from the edge for four
# hours -- the new glass icon was at the origin but Add to Home Screen still
# showed the old one. The HTML is max-age=0, so putting a content hash in the
# icon URL means any future icon change busts the cache by itself, with no purge
# and no waiting.
def _iconv(name: str) -> str:
    f = SITE / name
    if not f.exists():
        return f"/{name}"
    return f"/{name}?v={hashlib.sha256(f.read_bytes()).hexdigest()[:10]}"

# iOS launch images, generated by pipeline/make_splash_images.py. Read from the
# generated file rather than duplicated here, so regenerating the set cannot
# leave the markup pointing at files that no longer exist. Safe to concatenate
# into a str.format template: media queries contain no braces.
_SPLASH_LINKS = ""
_sl = HERE / "pipeline" / "splash_links.html"
if _sl.exists():
    _SPLASH_LINKS = "\n" + _sl.read_text().strip() + "\n"

PWA_HEAD = """
<link rel="manifest" href="/manifest.webmanifest">
<meta name="theme-color" content="#000000">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="R3000">
<link rel="apple-touch-icon" href="__ATI__">
<link rel="icon" href="__I192__" type="image/png">
<script src="/update.js" defer></script>
""".replace("__ATI__", _iconv("apple-touch-icon.png"))\
              .replace("__I192__", _iconv("icon-192.png")) + _SPLASH_LINKS

# Never passed through str.format: it is full of braces, and one stray format
# call would either raise or silently eat them.
UPDATE_JS = """// Tells a page that it is out of date, and offers a way out.
//
// An installed PWA on iOS can be resumed without ever performing a navigation,
// so nothing refetches and nothing checks for a new service worker. The page
// then sits on whatever data it loaded the first time, with no reload control
// anywhere in the standalone UI. That is how a refreshed panel stayed invisible
// on a phone while the server had been serving the new numbers for hours.
//
// So: compare the build this page was stamped with against the one the server
// is publishing now, on load and every time the tab or app becomes visible.
(function(){
  var el = document.querySelector('meta[name="x-build"]');
  var mine = el ? el.content : "";
  var shown = false;

  function offerReload(){
    if (shown) return;
    shown = true;
    var bar = document.createElement("div");
    bar.setAttribute("role", "status");
    bar.style.cssText =
      "position:fixed;left:0;right:0;bottom:0;z-index:99999;background:#111;" +
      "color:#fff;font:14px/1.4 -apple-system,system-ui,sans-serif;" +
      "padding:12px 14px;display:flex;gap:12px;align-items:center;" +
      "justify-content:center;box-shadow:0 -2px 12px rgba(0,0,0,.35)";
    var msg = document.createElement("span");
    msg.textContent = "Newer data is available.";
    var btn = document.createElement("button");
    btn.textContent = "Reload";
    btn.style.cssText =
      "background:#ff9900;color:#000;border:0;border-radius:6px;padding:7px 14px;" +
      "font:600 14px -apple-system,system-ui,sans-serif;cursor:pointer";
    btn.onclick = function(){
      btn.disabled = true;
      btn.textContent = "Reloading";
      var go = function(){ location.reload(); };
      // Drop every cache first, or the service worker just serves the same page
      // back and the banner returns.
      if (window.caches) {
        caches.keys().then(function(keys){
          return Promise.all(keys.map(function(k){ return caches.delete(k); }));
        }).then(go, go);
      } else { go(); }
    };
    bar.appendChild(msg);
    bar.appendChild(btn);
    document.body.appendChild(bar);
  }

  function check(){
    if (!mine) return;
    fetch("/version.json", {cache: "no-store"})
      .then(function(r){ return r.ok ? r.json() : null; })
      .then(function(v){ if (v && v.build && v.build !== mine) offerReload(); })
      .catch(function(){});
  }

  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.register("/sw.js").then(function(reg){
      if (reg.update) reg.update();
      document.addEventListener("visibilitychange", function(){
        if (!document.hidden && reg.update) reg.update();
      });
    }).catch(function(){});
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", check);
  } else { check(); }
  document.addEventListener("visibilitychange", function(){
    if (!document.hidden) check();
  });
})();


// ---- data-refresh indicator ------------------------------------------------
// While a pipeline rebuild is running, /status.json holds {"refreshing":true};
// this shows a small badge until it flips back to false, polling so it clears
// itself with no second deploy. Fails silent if status.json is absent.
(function(){
  var el=null, styled=false;
  function ensureStyle(){
    if(styled) return; styled=true;
    var s=document.createElement("style");
    s.textContent=
      '#nl-refresh{position:fixed;left:16px;bottom:16px;z-index:9998;display:flex;align-items:center;gap:9px;'+
      'font:500 13px/1.2 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;'+
      'padding:9px 15px;border-radius:999px;color:var(--ink,#f5f2ec);max-width:calc(100vw - 32px);'+
      'background:var(--panel,var(--raise,#1c1917));border:1px solid var(--rule,rgba(255,255,255,.15));'+
      'box-shadow:0 10px 28px -10px rgba(0,0,0,.55);opacity:0;transform:translateY(6px);'+
      'transition:opacity .3s ease,transform .3s ease;pointer-events:none}'+
      '#nl-refresh.in{opacity:1;transform:none}'+
      '#nl-refresh .sp{width:13px;height:13px;flex:0 0 auto;border-radius:50%;'+
      'border:2px solid var(--s1,#E0762F);border-top-color:transparent;animation:nlspin .8s linear infinite}'+
      '#nl-refresh b{color:var(--s1,#E0762F);font-weight:600}'+
      '@keyframes nlspin{to{transform:rotate(360deg)}}'+
      '@media(prefers-reduced-motion:reduce){#nl-refresh .sp{animation:none;border-top-color:var(--s1,#E0762F)}'+
      '#nl-refresh{transition:opacity .3s ease}}';
    document.head.appendChild(s);
  }
  function show(){
    ensureStyle();
    if(el) return;
    el=document.createElement("div"); el.id="nl-refresh"; el.setAttribute("role","status"); el.setAttribute("aria-live","polite");
    el.innerHTML='<span class="sp" aria-hidden="true"></span><span><b>Refreshing</b> the dataset… figures may change shortly</span>';
    document.body.appendChild(el); requestAnimationFrame(function(){el.classList.add("in");});
  }
  function hide(){ if(!el) return; el.classList.remove("in"); var e=el; el=null; setTimeout(function(){if(e&&e.parentNode)e.parentNode.removeChild(e);},350); }
  function poll(){
    fetch("/status.json?t="+Date.now(),{cache:"no-store"})
      .then(function(r){return r.ok?r.json():null;})
      .then(function(j){ (j&&j.refreshing)?show():hide(); })
      .catch(function(){hide();});
  }
  if(document.body) poll(); else addEventListener("DOMContentLoaded",poll);
  setInterval(poll,45000);
})();
"""

LANDING = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Bilaal Raja | Equity Research and Quantitative Analysis</title>
<meta name="description" content="Bilaal Raja. Cross-sectional equity screening built from primary SEC EDGAR filings: the full Russell 3000, metrics computed point in time, management commentary parsed alongside.">
<meta name="author" content="Bilaal Raja">
<link rel="canonical" href="https://bilaalraja.com/">
<meta property="og:type" content="profile">
<meta property="og:site_name" content="Bilaal Raja">
<meta property="og:title" content="Bilaal Raja | Equity Research and Quantitative Analysis">
<meta property="og:description" content="Cross-sectional equity screening built from primary SEC EDGAR filings. The full Russell 3000, metrics computed point in time, management commentary parsed alongside.">
<meta property="og:url" content="https://bilaalraja.com/">
<meta property="og:image" content="https://bilaalraja.com/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Bilaal Raja | Equity Research and Quantitative Analysis">
<meta name="twitter:description" content="Cross-sectional equity screening built from primary SEC EDGAR filings.">
<meta name="twitter:image" content="https://bilaalraja.com/og.png">
""" + PWA_HEAD + """
<script type="application/ld+json">
{{"@context":"https://schema.org","@type":"Person","name":"Bilaal Raja",
"url":"https://bilaalraja.com/","image":"https://bilaalraja.com/og.png",
"jobTitle":"Quality Scientist","description":"Equity research and quantitative analysis built from primary SEC filings.",
"alumniOf":{{"@type":"CollegeOrUniversity","name":"University of Manchester"}},
"knowsAbout":["Equity research","Quantitative analysis","SEC EDGAR filings","Factor investing","Financial data engineering"],
"sameAs":["https://linkedin.com/in/bilaalraja"]}}
</script>
__FONTS__
<style>
__TOKENS__
.wrap{{position:relative;z-index:1}}
@supports (corner-shape: squircle){{.card{{corner-shape:squircle}}}}
body{{background:var(--bg);color:var(--ink);font-family:var(--sans);font-size:15px;
 line-height:1.55;-webkit-font-smoothing:antialiased}}
.wrap{{max-width:760px;margin:0 auto;padding:64px 22px 80px}}
h1{{font-family:var(--serif);font-size:34px;font-weight:600;letter-spacing:-.021em;line-height:1.08;margin-bottom:6px;text-wrap:balance}}
/* Identity band. Tighter than the old hero: the masthead already carries the
   name, so this only has to say what the work is and how big it is. */
.ident{{margin:2px 0 26px}}
.sub{{color:var(--ink3);font-family:var(--mono);font-size:11.5px;letter-spacing:.04em;
 margin:0 0 12px}}
.lede{{color:var(--ink2);font-size:14.5px;line-height:1.6;margin:13px 0 0;max-width:58ch}}
/* The figures are context, not the point of the page, so they are set as a
   statement's key-figures block -- label left, figure right in tabular mono --
   rather than oversized tiles. */
.figs{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 44px;margin:24px 0 0}}
.figs>div{{display:flex;justify-content:space-between;align-items:baseline;gap:18px;
 padding:8px 0;border-bottom:1px solid var(--rule)}}
.figs dt{{color:var(--ink3);font-size:12.5px}}
.figs dd{{margin:0;font-family:var(--mono);font-size:13.5px;color:var(--ink);
 font-variant-numeric:tabular-nums;white-space:nowrap}}
/* Contents, not cards. Each entry is a ruled row: title, vintage right-aligned,
   description beneath. It carries five entries as readily as three, which the
   card row could not, and the accent appears in exactly one place -- the title
   on hover. */
.index{{margin:34px 0 0;border-top:1px solid var(--ink2)}}
.index a{{display:grid;grid-template-columns:minmax(0,1fr) auto;column-gap:26px;row-gap:5px;
 padding:17px 0;border-bottom:1px solid var(--rule);text-decoration:none;color:inherit}}
.index .t{{font-family:var(--serif);font-size:17.5px;line-height:1.25;transition:color .16s ease}}
.index .v{{font-family:var(--mono);font-size:10.5px;letter-spacing:.06em;text-transform:uppercase;
 color:var(--ink3);white-space:nowrap;text-align:right}}
.index .d{{grid-column:1/-1;color:var(--ink2);font-size:13.5px;line-height:1.62;max-width:70ch}}
.index a:hover .t,.index a:focus-visible .t{{color:var(--s1)}}
@media (max-width:620px){{
  .figs{{grid-template-columns:minmax(0,1fr)}}
  .index .v{{display:none}}
}}
/* Wide displays: a reading column, not a full-bleed one. A contents list wants a
   measure it can be read at, so this widens far less than a card grid would. */
@media (min-width:1000px){{
  .wrap{{max-width:940px;padding:76px 32px 92px}}
  .lede{{font-size:15.5px}}
  .figs{{grid-template-columns:repeat(3,minmax(0,1fr))}}
  .index .t{{font-size:19px}}
}}
@media (min-width:1500px){{
  .wrap{{max-width:1030px;padding:88px 32px 100px}}
  .lede{{font-size:16px}}
}}
footer{{margin-top:40px;padding-top:18px;border-top:1px solid var(--rule);
 font-family:var(--mono);font-size:12px;color:var(--ink3)}}
footer a{{color:var(--s1)}}
.rights{{display:block;margin-top:12px;padding-top:12px;border-top:1px solid var(--rule);
 max-width:76ch;line-height:1.7;font-size:11.5px}}
/* Wide displays. On a Studio Display this was a 540px column of content in a
   2000px viewport, with the three-tile pager clipped mid-card. Above 1000px there
   is no thumb to swipe with and no reason to page at all, so the pager becomes a
   plain grid and the dots go with it -- they would be controls for a scroll that
   no longer exists. Type steps up with the width; 14.5px at 5K reads small. */
@media (min-width:1000px){{
  .wrap{{max-width:1060px;padding:76px 32px 96px}}
  .pager{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;
    overflow:visible;scroll-snap-type:none;margin:0;padding:0}}
  .card{{flex:0 1 auto;scroll-snap-align:none;padding:22px 24px}}
  .pnav{{display:none}}
  .lede{{font-size:15.5px;max-width:62ch}}
  .stats b{{font-size:25px}}
  .stats span{{font-size:10.5px}}
  .card h2{{font-size:17px}}
}}
@media (min-width:1500px){{
  .wrap{{max-width:1180px;padding:88px 32px 104px}}
  .lede{{font-size:16.5px}}
  .stats b{{font-size:28px}}
  .card h2{{font-size:18px}}
}}
</style></head><body><div class="wrap">
__MASTHEAD__
<!-- The name is already the masthead, top left. Repeating it as a display
     heading said nothing new and pushed the actual work below the fold on a
     phone, so the identity is one band: what this is, the four numbers that
     size it, and why it exists. -->
<section class="ident">
  <p class="sub">Equity research &middot; quantitative analysis</p>
  <p class="lede">Built from primary sources. The universe, the factor
  construction and the validation are my own, assembled from SEC XBRL company
  facts rather than a vendor feed.</p>
  <dl class="figs">
    <div><dt>Companies</dt><dd>{n}</dd></div>
    <div><dt>Market capitalisation</dt><dd>${mcap}tn</dd></div>
    <div><dt>Metrics computed</dt><dd>{metrics}</dd></div>
    <div><dt>Sectors</dt><dd>{sectors}</dd></div>
    <div><dt>Filings through</dt><dd>{latest_filing}</dd></div>
    <div><dt>Prices as at</dt><dd>{price_date}</dd></div>
  </dl>
</section>

<nav class="index" aria-label="Contents">
<a href="/russell3000/">
  <span class="t">Russell 3000 Cross-Section</span>
  <span class="v">rebuilt {built_human}</span>
  <span class="d">{n} companies with computable trailing-twelve-month fundamentals,
  screened on 35 metrics with sector-neutral percentile ranking and a composite score.</span>
</a>
<a href="/commentary/">
  <span class="t">Results Commentary</span>
  <span class="v">rebuilt {built_human}</span>
  <span class="d">Management&rsquo;s own discussion of results, extracted from 10-Q and 10-K
  filings and matched to the reported figures.</span>
</a>
<a href="/gate-exit/">
  <span class="t">This strategy put to the test</span>
  <span class="v">51 formations</span>
  <span class="d">A screen where the criterion that buys a company is the criterion that
  sells it &mdash; held while it keeps passing, dropped the quarter it stops. Every buy and
  sell across 51 quarterly formations since 2013.</span>
</a>
<a href="/rates/">
  <span class="t">US Treasury yields &amp; the Fed</span>
  <span class="v">rates</span>
  <span class="d">The Fed funds rate against 2, 10 and 30-year Treasury yields since 2015 &mdash;
  an interactive chart you can drag to read any day, with the 10y&ndash;2y spread.</span>
</a>
<a href="/methodology/">
  <span class="t">How this was built</span>
  <span class="v">method</span>
  <span class="d">Universe construction, point-in-time discipline, metric definitions, and the
  fourteen defects found by checking output against reality.</span>
</a>
</nav>

<footer>
Built from SEC XBRL company facts and market prices.<br>
<a href="https://linkedin.com/in/bilaalraja">linkedin.com/in/bilaalraja</a>
<span class="rights">&copy; {year} Bilaal Raja. The universe construction, factor
definitions, analysis and code on this site are my own work and are not licensed
for reuse. The underlying SEC filing data is public domain. Published as a
personal project; nothing here is investment advice or a recommendation to buy
or sell any security.</span>
</footer>
</div>
__TICKERJS__</body></html>
"""



# ----------------------------------------------------------------- metadata
# Open Graph is the one that actually matters here: without it a link pasted
# into LinkedIn or an email renders as a bare URL instead of a card.
DESCRIPTIONS = {
 "russell3000": ("Russell 3000 Cross-Section | Bilaal Raja",
   "Every relevant line item pulled from SEC EDGAR filings for the Russell "
   "3000, with key financial metrics computed point in time. {companies} companies, "
   "35 metrics, sector-neutral percentile ranking."),
 "commentary": ("Russell 3000 Results Commentary | Bilaal Raja",
   "Management's own discussion of results, parsed from 10-Q and 10-K filings "
   "for thousands of US listed companies and matched to the reported figures."),
 "gate-exit": ("The Gate Exit Rule | Bilaal Raja",
   "A quality screen where the criterion that buys a company is the criterion "
   "that sells it. Six gates, 25 names, held while they keep passing. Every buy "
   "and sell across 51 quarterly formations, December 2013 to July 2026."),
 "rates": ("US Treasury Yields & the Fed | Bilaal Raja",
   "The effective federal funds rate against 2, 10 and 30-year US Treasury yields, "
   "daily since 2015 — an interactive chart with the 10y-2y spread. Data from the "
   "US Treasury and the New York Fed."),
}


def inject_meta(html: str, path: str, domain: str, companies: str = "",
                build: str = "") -> str:
    if path not in DESCRIPTIONS:
        return html
    title, desc = DESCRIPTIONS[path]
    # the count is the live one, not a number frozen into the template
    if "{companies}" in desc:
        if not companies:
            sys.exit("inject_meta: no company count for the OG description")
        desc = desc.format(companies=companies)
    url = f"https://{domain}/{path}"
    tags = f"""
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="description" content="{desc}">
<meta name="author" content="Bilaal Raja">
<meta name="x-build" content="{build}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Bilaal Raja">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="https://{domain}/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="https://{domain}/og.png">
""" + PWA_HEAD
    # insert straight after the existing <title>...</title>
    i = html.find("</title>")
    html = html[:i + 8] + tags + html[i + 8:] if i != -1 else tags + html
    # The phone rules go LAST in <head>, not with the meta tags at the top. The
    # tags are inserted immediately after <head>, which puts them ahead of each
    # page's own stylesheet -- and a rule of equal specificity that arrives first
    # loses. Appending before </head> lets these override without !important.
    css = f"<style>{brand.RESPONSIVE_CSS}{brand.SPLASH_CSS}</style>\n"

    # Where the body effectively begins. The dashboard has no <html>, <head> or
    # <body> at all -- it opens straight at <meta charset> and lets the parser
    # imply the rest -- so fall back to the first block element.
    k = html.find("<body")
    if k != -1:
        k = html.find(">", k) + 1
    else:
        cands = [html.find(t) for t in ("<main", "<header", "<nav", "<section", "<div")]
        cands = [c for c in cands if c != -1]
        k = min(cands) if cands else -1

    # The CSS must precede the content it hides. Appending it at the end when
    # there is no </head> meant the dashboard painted all 2 MB of itself and
    # only then read the rule putting the splash over the top -- a visible flash
    # of the whole page before the splash appeared. So without a </head> the
    # style goes immediately before the first content instead.
    j = html.find("</head>")
    if j != -1:
        html = html[:j] + css + html[j:]
        if k != -1 and k > j:
            k += len(css)
    elif k != -1:
        html = html[:k] + css + html[k:]
        k += len(css)
    else:
        html += css

    if k != -1:
        html = html[:k] + brand.SPLASH_HTML + html[k:]
    return html


def _brandify(html: str) -> str:
    """Insert the shared tokens after formatting.

    The templates run through str.format, and CSS is nothing but braces, so the
    palette is carried as a placeholder and swapped in here instead.
    """
    # The live 8-K strip belongs to the cross-section, which injects it itself in
    # make_r3k_dash. It was arriving here too, so the landing page, the 404 and
    # the methodology note all carried a filings ticker that has nothing to do
    # with what is on them -- and each fetched SEC on load to fill it.
    return (html.replace("__TOKENS__", brand.TOKENS + brand.TRANSITION_CSS + brand.MASTHEAD_CSS
                          + brand.RESPONSIVE_CSS + brand.SPLASH_CSS)
                .replace("__MASTHEAD__", brand.SPLASH_HTML + "__MASTHEAD__", 1)
                .replace("__FONTS__", brand.FONTS)
                .replace("__MASTHEAD__", brand.masthead())
                .replace("__TICKERJS__", brand.NAV_JS))


def write_sitemap(site: Path, domain: str, paths, lastmod: str):
    urls = "".join(
        f"  <url><loc>https://{domain}/{p}</loc><lastmod>{lastmod}</lastmod>"
        f"<changefreq>monthly</changefreq><priority>{pr}</priority></url>\n"
        for p, pr in paths)
    (site / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + urls + "</urlset>\n")


# ---------------------------------------------------------------- referrers
# One landing page per contact. Each fires the analytics beacon under its own
# path, then forwards to the dashboard, so "did this person open it" becomes a
# page view you can actually see rather than a guess.
REF_PAGE = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<title>Russell 3000 Cross-Section</title>
<meta name="robots" content="noindex,nofollow">
<link rel="canonical" href="https://{domain}{target}">
<style>body{{background:#131312;color:#8b8a80;font:14px -apple-system,sans-serif;
 display:flex;align-items:center;justify-content:center;height:100vh;margin:0}}</style>
</head><body>
<p>Opening&#8230; <a href="{target}">continue</a></p>
<script>
// Delay briefly so the analytics beacon fires before we navigate away.
addEventListener("load",()=>setTimeout(()=>location.replace("{target}"),350));
</script>
</body></html>
"""


def build_referrers(site: Path, domain: str, target: str = "/russell3000") -> list:
    src = Path(__file__).resolve().parent / "contacts.txt"
    if not src.exists():
        return []
    out = []
    for line in src.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [x.strip() for x in line.split(",")]
        slug = parts[0]
        who = ", ".join(parts[1:]) or "-"
        d = site / "r" / slug
        d.mkdir(parents=True, exist_ok=True)
        (d / "index.html").write_text(REF_PAGE.format(domain=domain, target=target))
        out.append((slug, who))
    return out


METHODOLOGY = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Methodology | Bilaal Raja</title>
<meta name="description" content="How the Russell 3000 cross-section is built from SEC EDGAR filings: universe construction, point-in-time discipline, metric definitions, and the defects found along the way.">
<link rel="canonical" href="https://{domain}/methodology">
<meta property="og:type" content="article">
<meta property="og:title" content="Methodology | Bilaal Raja">
<meta property="og:description" content="How the cross-section is built, and the fourteen defects found by checking output against reality.">
<meta property="og:url" content="https://{domain}/methodology">
<meta property="og:image" content="https://{domain}/og.png">
<meta name="twitter:card" content="summary_large_image">
""" + PWA_HEAD + """
__FONTS__
<style>
__TOKENS__
body{{background:var(--bg);color:var(--ink);font-family:var(--sans);font-size:16px;
 line-height:1.68;-webkit-font-smoothing:antialiased}}
.wrap{{max-width:760px;margin:0 auto;padding:56px 22px 90px}}
a{{color:var(--s1)}}
.back{{font-family:var(--mono);font-size:12px;letter-spacing:.06em;text-decoration:none;
 display:inline-block;margin-bottom:34px}}
h1{{font-size:31px;letter-spacing:-.018em;line-height:1.14;margin-bottom:10px}}
.lede{{color:var(--ink2);font-size:17px;margin-bottom:14px}}
.stamp{{font-family:var(--mono);font-size:12px;color:var(--ink3);
 padding-bottom:26px;border-bottom:1px solid var(--rule);margin-bottom:34px}}
h2{{font-size:20px;letter-spacing:-.012em;margin:40px 0 12px}}
h3{{font-size:15.5px;margin:26px 0 6px}}
p{{margin-bottom:14px;color:var(--ink2)}}
p strong,li strong{{color:var(--ink);font-weight:600}}
ul{{margin:0 0 16px 20px}} li{{margin-bottom:9px;color:var(--ink2)}}
code{{font-family:var(--mono);font-size:.88em;background:var(--panel);
 padding:1px 5px;border-radius:5px;color:var(--ink)}}
.note{{background:var(--panel);border-left:3px solid var(--s1);border-radius:12px;
 padding:15px 18px;margin:22px 0}}
.note p:last-child{{margin-bottom:0}}
ol.defects{{list-style:none;counter-reset:d;margin:0;padding:0}}
ol.defects li{{counter-increment:d;background:var(--panel);border:1px solid var(--rule2);
 border-radius:14px;padding:16px 18px;margin-bottom:10px}}
ol.defects li::before{{content:counter(d,decimal-leading-zero);font-family:var(--mono);
 font-size:11px;color:var(--s1);display:block;margin-bottom:5px;letter-spacing:.08em}}
ol.defects b{{display:block;color:var(--ink);font-size:15.5px;margin-bottom:5px}}
ol.defects p{{margin:0;font-size:14.5px}}
footer{{margin-top:52px;padding-top:20px;border-top:1px solid var(--rule);
 font-family:var(--mono);font-size:11.5px;color:var(--ink3);line-height:1.7}}
</style></head><body><div class="wrap">
__MASTHEAD__
<a class="back" href="/">&larr; BILAALRAJA.COM</a>
<h1>How this was built</h1>
<p class="lede">The universe, the point-in-time discipline, the metric definitions,
and the defects I found along the way.</p>
<div class="stamp">{n} companies &middot; filings to {latest_filing} &middot;
prices {price_date} &middot; rebuilt {built_human}</div>

<h2>What this is, and what it is not</h2>
<p>It is a <strong>reconstruction</strong>, not the licensed index. Constituents are
the top 3,000 US-listed companies by market capitalisation on the price date,
rebuilt from SEC filings using Russell's own published rule. It is not a
membership list, and where FTSE Russell's actual reconstitution differs, mine
will differ with it.</p>
<p>Of {universe} candidates, <strong>{n} carry enough filed data</strong> to compute a
trailing twelve month figure. The remaining {skipped} are absent, not zero. That
distinction matters: dropping them silently would bias every cross-sectional
statistic on the page.</p>

<h2>Point in time</h2>
<p>Every figure is <strong>as filed</strong>, not as later restated. A company that
revised its June quarter in October shows what it originally reported.</p>
<ul>
<li>TTM is reconstructed from <strong>four contiguous quarters</strong>, accepted
only where the window spans 240 to 300 days. Anything outside that is a gap, and
a gap is a null rather than a guess.</li>
<li>Filers on a 52/53 week calendar produce two quarters ending days apart.
Those are <strong>deduplicated by period end</strong>, otherwise a quarter is
double counted.</li>
<li>Concept selection is <strong>duration-aware</strong>. An instantaneous balance
sheet fact and a quarterly flow carry the same tag in places, and taking either
without checking the period type silently mixes stocks with flows.</li>
<li>Prices are a <strong>single dated snapshot</strong>. Fundamentals are as
filed. The two are not contemporaneous and the page says so.</li>
</ul>

<h2>Metric definitions worth stating</h2>
<h3>Return on capital employed, not invested capital</h3>
<p>ROCE uses equity plus debt. Subtracting cash to reach invested capital
collapses the denominator on cash-rich balance sheets and produces returns in
the thousands of percent, which is arithmetic rather than insight. Capital
employed is guarded at a floor so a near-zero denominator cannot manufacture a
ranking.</p>
<h3>Banks do not report revenue</h3>
<p><strong>{banks} banks carry no revenue tag at all.</strong> They use net
interest income plus non-interest income instead. Anyone screening the full
market on a revenue multiple without handling this is quietly excluding an
entire sector, and will not notice.</p>
<h3>Winsorisation and sector-neutral ranking</h3>
<p>Raw cross-sectional ranges are unusable. Percentiles are computed within
sector so a utility is compared with utilities, and extreme values are clipped
rather than dropped, so the company stays in the ranking without dominating it.</p>

<h2>Sector is a filter, not a colour</h2>
<p>Twelve categorical hues on three thousand overlapping points is not a design
preference, it is a measurable failure. Run through a colourblind separation
check, twelve hues score a worst all-pairs OKLab distance of <strong>2.0</strong>
against a threshold of 8. Even four hues only pass with a carefully chosen set.</p>
<p>So the main chart is a neutral density cloud and one sector highlights at a
time, which is always a two-category comparison and always separable. Comparing
sectors is done with small multiples, which is the prescribed route when
all-pairs separation fails.</p>

<h2>Thirteen defects, and how they were found</h2>
<div class="note"><p>Every one of these was caught by checking output against
reality, not by reading code. None of them raised an error. That is the point
worth taking from this section: a pipeline that runs cleanly and reports success
can still be wrong in ways only a sanity check will surface.</p></div>
<ol class="defects">
<li><b>American depositary receipts valued at the ordinary share count</b>
<p>One company appeared at a $555bn market capitalisation. The share count was
ordinary shares; the price was per ADS. Fixed by cross-checking counts against
an independent source and excluding on an ADR signature.</p></li>
<li><b>Reverse splits left share counts unadjusted</b>
<p>545 names carried pre-split counts against post-split prices. Fixed by
applying a cumulative split factor from the period end forward.</p></li>
<li><b>Multi-class filers were invisible</b>
<p>Several of the largest companies in the market never became candidates,
because their share counts are dimensioned by class and do not appear in the
undimensioned cover-page data. Fixed by broadening the candidate pool to every
tickered filer rather than trusting one tag.</p></li>
<li><b>A truncated filing history deleted the banking sector</b>
<p>The stored form list holds only the most recent filings. Testing "does this
company file a 10-K" against it excluded frequent filers whose annual report had
scrolled off the end. Fixed by removing the positive form test entirely.</p></li>
<li><b>Ticker selection preferred baby bonds to common stock</b>
<p>A utility resolved to its preferred note rather than its common line, valuing
it at $3.3bn instead of $29.1bn. Fixed by preferring the ticker that carries a
reported share count, which only common equity does.</p></li>
<li><b>Cash flow read from the wrong accessor</b>
<p>Operating cash flow resolved for 18 quarters where a different accessor found
71. Free cash flow coverage rose from 0.8% to 81.7% once corrected.</p></li>
<li><b>Tag migration produced negative quarters</b>
<p>A revenue standard change mid-history produced negative implied quarters when
differencing cumulative figures. Now guarded: a negative quarter inside a TTM
window invalidates the window rather than propagating.</p></li>
<li><b>Log axes on raw percentiles</b>
<p>A second-percentile value near 1e-9 stretched an axis across nine decades and
compressed every real observation into a line. Found only by rendering the page
and looking at it.</p></li>
<li><b>A grouped operation silently misaligned</b>
<p>A pandas grouped apply returned results in a different order than the frame it
was assigned to, so a large-cap growth name scored 85.9 on a cheapness screen.
Caught by a sanity anchor; fixed by ranking within group directly.</p></li>
<li><b>Footnotes returned instead of commentary</b>
<p>The first extraction scored 93% on a structural check while returning
accounting footnotes for roughly a third of companies. Measured against a second
version on identical companies, the rate of passages leading with results went
from 42.8% to 65.0%.</p></li>
<li><b>One filer's commentary collapsed to boilerplate</b>
<p>A 171,000 character section reduced to 5,598 characters of front matter across
that filer's entire history, because the heading anchor matched too early. Fixed
with tiered anchors and a minimum-length test before accepting a narrower slice.</p></li>
<li><b>Background work killed by a foreground timeout</b>
<p>A polling loop hit a timeout, and the resulting signal took the whole process
group with it, losing thousands of in-memory results. Fixed by detaching the
session and checkpointing to disk.</p></li>
<li><b>A stale tier file silently narrowed a queue</b>
<p>A priority filter read tiering written by an earlier run and queued 5,874 items
instead of 25,548. It completed successfully, which is what made it dangerous.</p></li>
</ol>

<h2>What it cannot tell you</h2>
<ul>
<li>It is a <strong>snapshot</strong>. There is no history and no time series, so
nothing here supports a trend or a backtest.</li>
<li>Prices and fundamentals are <strong>not contemporaneous</strong>.</li>
<li>Companies report on <strong>different calendars</strong>. A comparison across
the cross-section compares quarters ending at different dates.</li>
<li>Business development companies and a small number of other structures are
<strong>excluded or misclassified</strong> by the SIC-derived sector mapping.</li>
<li>A metric that is null is <strong>missing, not zero</strong>, and is excluded
from ranking rather than treated as the worst value.</li>
</ul>

<footer>
Built from SEC XBRL company facts and market prices.
&copy; {year} Bilaal Raja. The universe construction, factor definitions, analysis
and code are my own work and are not licensed for reuse. The underlying SEC
filing data is public domain. Published as a personal project; nothing here is
investment advice or a recommendation to buy or sell any security.
</footer>
__TICKERJS__</div></body></html>
"""


NOT_FOUND = """<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Not found | Bilaal Raja</title>
<meta name="robots" content="noindex">
__FONTS__
<style>
__TOKENS__
body{{background:var(--bg);color:var(--ink);font-family:var(--sans);
 min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}}
.c{{max-width:38ch}}
h1{{font-family:var(--serif);font-size:30px;font-weight:600;letter-spacing:-.02em;margin-bottom:9px}}
p{{color:var(--ink3);font-size:15px;line-height:1.6;margin-bottom:20px}}
.n{{font-family:var(--mono);font-size:11.5px;letter-spacing:.14em;color:var(--ember);
 margin-bottom:14px}}
a{{color:var(--ember);font-family:var(--mono);font-size:12.5px}}
</style></head><body><div class="c">
<div class="n">404</div>
<h1>Nothing here</h1>
<p>That page does not exist. It may have been renamed, or the link may have been
mistyped.</p>
<a href="/">&larr; BILAALRAJA.COM</a>
__TICKERJS__</div></body></html>
"""


# ---------------------------------------------------------------------- PWA
# iOS has honoured web app manifests since 16.4, so this installs as a real
# standalone app rather than a bookmark. The apple-* tags stay for older iOS.

MANIFEST = """{{
  "name": "Russell 3000 Cross-Section",
  "short_name": "R3000",
  "description": "Cross-sectional screening for the Russell 3000, built from SEC EDGAR filings.",
  "start_url": "/russell3000/",
  "scope": "/",
  "display": "standalone",
  "orientation": "any",
  "background_color": "#000000",
  "theme_color": "#000000",
  "icons": [
    {{"src": "__I192__", "sizes": "192x192", "type": "image/png", "purpose": "any"}},
    {{"src": "__I512__", "sizes": "512x512", "type": "image/png", "purpose": "any"}},
    {{"src": "__I512__", "sizes": "512x512", "type": "image/png", "purpose": "maskable"}}
  ]
}}"""

# The commentary page is 12MB and is deliberately not precached; caching it
# would blow past what iOS is willing to keep for a web app.
SW = """const V="r3k-{built}-r2";

// Cloudflare Pages 308s /russell3000 to /russell3000/. A response that followed
// a redirect carries redirected:true, and Safari refuses to accept one of those
// for a navigation request. So: precache the canonical trailing-slash paths, and
// rebuild every response before it is cached or returned, which clears the flag.
const SHELL=["/","/russell3000/","/learn/","/methodology/","/manifest.webmanifest",
             "/icon-192.png","/icon-512.png","/apple-touch-icon.png"];

async function plain(res){{
  if(!res) return res;
  const body=await res.arrayBuffer();
  return new Response(body,{{status:res.status,statusText:res.statusText,
                            headers:res.headers}});
}}

self.addEventListener("install",e=>{{
  e.waitUntil(caches.open(V).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting()));
}});

self.addEventListener("activate",e=>{{
  e.waitUntil(caches.keys()
    .then(ks=>Promise.all(ks.filter(k=>k!==V).map(k=>caches.delete(k))))
    .then(()=>self.clients.claim()));
}});

async function navigate(req){{
  try{{
    const res=await fetch(req);
    const fixed=await plain(res);
    const c=await caches.open(V);
    c.put(req,fixed.clone());
    return fixed;
  }}catch(err){{
    // Offline. Look for this page under both spellings of its path, since the
    // shell is precached with a trailing slash and a link may omit it.
    //
    // What must not happen is falling back to "/". Returning the landing page
    // for a different URL does not read as an offline page, it reads as the
    // link being broken: following the cross-section and arriving back at the
    // front page looks like a loop, and it hides the real cause. Fail honestly
    // instead and let the browser show its own offline page.
    const u=new URL(req.url);
    const alt=u.pathname.endsWith("/") ? u.pathname.slice(0,-1) : u.pathname+"/";
    const hit=await caches.match(req)
           || await caches.match(u.pathname)
           || await caches.match(alt);
    return hit ? await plain(hit) : Response.error();
  }}
}}

async function asset(req){{
  const hit=await caches.match(req);
  const net=fetch(req).then(async res=>{{
    if(res && res.status===200){{
      const fixed=await plain(res);
      const c=await caches.open(V);
      c.put(req,fixed.clone());
      return fixed;
    }}
    return res;
  }}).catch(()=>hit);
  return hit || net;
}}

self.addEventListener("fetch",e=>{{
  const r=e.request;
  if(r.method!=="GET") return;
  const u=new URL(r.url);
  if(u.origin!==location.origin) return;
  if(u.pathname.startsWith("/commentary")) return;   // 12MB, not worth caching
  // The freshness check must never be answered from this cache. asset() is
  // stale-while-revalidate, so serving version.json from here would compare a
  // stale page against a stale version file and conclude all was well.
  if(u.pathname==="/version.json"||u.pathname==="/update.js"||u.pathname==="/status.json") return;
  e.respondWith(r.mode==="navigate" ? navigate(r) : asset(r));
}});
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-build", action="store_true",
                    help="stage existing HTML without regenerating from data")
    a = ap.parse_args()

    if not a.no_build:
        print("rebuilding dashboard from current data ...")
        r = subprocess.run([PY, str(SRC / "make_r3k_dash.py")],
                           capture_output=True, text=True, cwd=SRC)
        sys.stdout.write(r.stdout)
        if r.returncode:
            sys.stderr.write(r.stderr)
            sys.exit("build failed — nothing staged, site/ left untouched")
        # regenerate the rates page from the latest history (offline; the network
        # fetch lives in refresh.py). Non-fatal if the data file is absent.
        if (SRC / "rates_history.json").exists():
            print("regenerating rates page ...")
            rr = subprocess.run([PY, str(SRC / "make_rates.py")],
                                capture_output=True, text=True, cwd=SRC)
            sys.stdout.write(rr.stdout)
            if rr.returncode:
                sys.stderr.write(rr.stderr)

    # One id per published state, taken from the sources before staging so it is
    # not a hash of a file that ends up containing it. Everything that has to
    # agree on "which build is this" uses this value: the page's own meta tag,
    # version.json, and the service worker cache name.
    #
    # This used to hash the dashboard alone, which is too narrow. The landing
    # page, the methodology and the case study are all templated inside this
    # file, so editing one of them left the dashboard untouched, produced a
    # byte-identical sw.js, and the browser saw no update: the service worker
    # went on serving the precached old page while the server held the new one.
    # A reload then mixes a stale shell with fresh content, which is exactly the
    # failure the version is supposed to prevent. Hash every page source and
    # this file, so any change to what gets published moves the id.
    _h = hashlib.sha1()
    for _f in sorted({p[0] for p in PAGES} | {Path(__file__).resolve()}):
        if _f.exists():
            _h.update(_f.read_bytes())
    BUILD = _h.hexdigest()[:10]

    SITE.mkdir(exist_ok=True)
    meta, total = {}, 0
    for src, path, title in PAGES:
        if not src.exists():
            print(f"  SKIP {title}: {src} not found")
            continue
        html = src.read_text(errors="replace")
        if "dashboard" in src.name:
            meta = meta_from_dashboard(html)
        html, n = rewrite_links(html)
        html = inject_meta(html, path, DOMAIN, f"{meta['n']:,}", BUILD)
        d = SITE / path
        d.mkdir(parents=True, exist_ok=True)
        (d / "index.html").write_text(html)
        mb = len(html) / 1e6
        total += mb
        print(f"  /{path:<14} {mb:6.2f} MB   {n} artifact link(s) localised")

    if not meta:
        sys.exit("could not read META from the dashboard — landing page not written")
    pretty = dict(meta, n=f"{meta['n']:,}", year=meta["built"][:4], domain=DOMAIN,
                  universe=f"{meta['universe']:,}", skipped=f"{meta['skipped']:,}",
                  mcap=f"{meta['total_mcap']/1000:.1f}",
                  banks=f"{meta['banks']:,}")
    (SITE / "index.html").write_text(_brandify(LANDING.format(**pretty)))
    print(f"  /              {len(LANDING)/1e3:6.2f} KB   landing page")

    # CNAME: GitHub Pages custom domain.  _headers: Netlify/Cloudflare.
    # .nojekyll: stops Pages trying to process the files as a Jekyll site.
    (SITE / "CNAME").write_text(DOMAIN + "\n")
    (SITE / "_headers").write_text(
        "/*\n  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: strict-origin-when-cross-origin\n"
        # a cached sw.js or version.json is a stale page nobody can clear
        "/sw.js\n  Cache-Control: no-store\n"
        "/version.json\n  Cache-Control: no-store\n"
        "/update.js\n  Cache-Control: no-store\n"
          "/status.json\n  Cache-Control: no-store\n"
        "/api/*\n  Cache-Control: no-store\n")
    (SITE / ".nojekyll").write_text("")
    (SITE / "manifest.webmanifest").write_text(
        MANIFEST.format().replace("__I192__", _iconv("icon-192.png"))
                         .replace("__I512__", _iconv("icon-512.png")))
    # The cache name used to be the build date alone, which is one value per
    # day however many times the site is published. Two publishes in a day then
    # produced a byte-identical sw.js, so the browser saw no update: install
    # never re-ran, activate never purged, and the shell precached by the first
    # publish stayed. That is how a refreshed panel could sit behind a stale
    # cached page. Hash the dashboard so every publish is its own version.
    (SITE / "sw.js").write_text(
        SW.format(built=f"{meta['built']}-{BUILD}"))
    (SITE / "version.json").write_text(json.dumps(
        {"build": BUILD, "built": meta["built"],
         "price_date": meta["price_date"]}) + "\n")
    (SITE / "update.js").write_text(UPDATE_JS)

    # The ticker gets raw filings from SEC and has to work out which are ours.
    # Shipping the lookup as a static file keeps the edge function stateless.
    scored = json.loads((SRC / "r3k_scored.json").read_text())
    ciks = {str(int(r["cik"])): [r["ticker"], r.get("name") or r["ticker"],
                                 round(float(r.get("mcap") or 0), 1)]
            for r in scored if r.get("cik") and r.get("ticker")}
    (SITE / "ciks.json").write_text(json.dumps(ciks, separators=(",", ":")))
    print(f"  ciks.json: {len(ciks)} companies "
          f"({(SITE / 'ciks.json').stat().st_size/1024:.0f} KB)")
    # Without this, Cloudflare Pages answers unknown paths with the landing page
    # and a 200, which Google reads as a soft 404 and may index as a duplicate.
    (SITE / "404.html").write_text(_brandify(NOT_FOUND.format()))
    (SITE / "methodology").mkdir(parents=True, exist_ok=True)
    (SITE / "methodology" / "index.html").write_text(_brandify(METHODOLOGY.format(**pretty)))
    print(f"  /methodology   {len(METHODOLOGY)/1e3:6.2f} KB")
    # Company pages are generated here rather than by hand: 2,500 pages that
    # only refresh when someone remembers is the commentary problem again.
    r = subprocess.run([PY, str(SRC / "make_case_study.py")],
                       capture_output=True, text=True, cwd=SRC)
    sys.stdout.write(r.stdout)
    if r.returncode:
        sys.stderr.write(r.stderr)
        sys.exit("case study failed - nothing further staged")

    r = subprocess.run([PY, str(SRC / "make_company_pages.py")],
                       capture_output=True, text=True, cwd=SRC)
    sys.stdout.write(r.stdout)
    if r.returncode:
        sys.stderr.write(r.stderr)
        sys.exit("company pages failed - nothing further staged")

    # Every company page in the sitemap. Without this they are unreachable
    # except by guessing the URL, which wastes the entire point of having them.
    tickers = sorted(d.name for d in (SITE / "c").iterdir() if d.is_dir()) \
              if (SITE / "c").exists() else []
    write_sitemap(SITE, DOMAIN,
                  [("", "1.0"), ("russell3000", "0.9"), ("commentary", "0.8"),
                   ("methodology", "0.85"), ("learn", "0.85"), ("gate-exit", "0.85"),
                   ("rates", "0.8")]
                  + [(f"c/{t}", "0.6") for t in tickers],
                  meta["built"])
    n_urls = (SITE / "sitemap.xml").read_text().count("<url>")
    print(f"  sitemap: {n_urls} URLs")
    (SITE / "robots.txt").write_text(
        "User-agent: *\nDisallow: /r/\nAllow: /\n"
        f"Sitemap: https://{DOMAIN}/sitemap.xml\n")

    refs = build_referrers(SITE, DOMAIN)
    if refs:
        print(f"\n{len(refs)} tracked link(s):")
        for slug, who in refs:
            print(f"   https://{DOMAIN}/r/{slug:<10}  {who}")

    print(f"\nstaged {total:.2f} MB in {SITE}")
    print(f"filings to {meta['latest_filing']} · prices {meta['price_date']}"
          f" · rebuilt {meta['built_human']} · {meta['n']} companies")
    print(f"\nlive at  https://{DOMAIN}/russell3000  once pushed")
    print("next:    git add -A && git commit -m 'refresh' && git push")


if __name__ == "__main__":
    main()
